INSERT INTO GENERO VALUES('M', 'Masculino');
INSERT INTO GENERO VALUES('F', 'Femenino');
INSERT INTO GENERO VALUES('X', 'No Binario');

INSERT INTO TIPO_RESIDENCIA VALUES('F', 'Familiar');
INSERT INTO TIPO_RESIDENCIA VALUES('P', 'Propia sin Hipoteca');
INSERT INTO TIPO_RESIDENCIA VALUES('H', 'Propia con Hipoteca');
INSERT INTO TIPO_RESIDENCIA VALUES('A', 'Arrendada');

INSERT INTO ACTIVIDAD_ECONOMICA VALUES(1, 'Jubilado');
INSERT INTO ACTIVIDAD_ECONOMICA VALUES(2, 'Empleado');
INSERT INTO ACTIVIDAD_ECONOMICA VALUES(3, 'Transportador');
INSERT INTO ACTIVIDAD_ECONOMICA VALUES(4, 'Independiente');
INSERT INTO ACTIVIDAD_ECONOMICA VALUES(8, 'Hogar');

INSERT INTO TIPO_CONTRATO VALUES('F', 'Fijo');
INSERT INTO TIPO_CONTRATO VALUES('I', 'Indefinido');
INSERT INTO TIPO_CONTRATO VALUES('O', 'Otro');

INSERT INTO NIVEL_ESTUDIO VALUES('N', 'Ninguno');
INSERT INTO NIVEL_ESTUDIO VALUES('P', 'Primaria');
INSERT INTO NIVEL_ESTUDIO VALUES('S', 'Secundaria');
INSERT INTO NIVEL_ESTUDIO VALUES('T', 'Técnico/Tecnólogo');
INSERT INTO NIVEL_ESTUDIO VALUES('U', 'Universitario/Posgrado');

INSERT INTO TIPO_INMUEBLE VALUES('N', 'Ninguno');
INSERT INTO TIPO_INMUEBLE VALUES('C', 'Casa');
INSERT INTO TIPO_INMUEBLE VALUES('A', 'Apartamento');
INSERT INTO TIPO_INMUEBLE VALUES('B', 'Bodega');

INSERT INTO ESTADO_CIVIL VALUES('C', 'Casado');
INSERT INTO ESTADO_CIVIL VALUES('V', 'Viudo');
INSERT INTO ESTADO_CIVIL VALUES('T', 'Soltero');
INSERT INTO ESTADO_CIVIL VALUES('U', 'Unión Libre');
INSERT INTO ESTADO_CIVIL VALUES('S', 'Separado');